import { NextResponse } from 'next/server'
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'
import fs from 'node:fs/promises'
import path from 'node:path'
import { Resend } from 'resend'
import { z } from 'zod'
import { createClient } from '@/lib/supabase/server'

const schema = z.object({ submissionId: z.string().uuid(), applicantName: z.string().min(1), jobTitle: z.string().trim().min(1).refine(value => value !== 'Assessed position', 'Select the actual position.'), startDate: z.string().min(1), dutyStation: z.string().min(1), department: z.string().min(1), contractType: z.string().min(1), documentDeadline: z.string().min(1), acceptanceDeadline: z.string().min(1) })
const HR_CONTACT = 'Reintje van Haeringen\nHuman Resources\nCARE International'
const resend = new Resend(process.env.RESEND_API_KEY)
function candidateIdFragment(id: string) { return id.replaceAll('-', '').slice(0, 8).toUpperCase() }
function wrap(text: string, max = 88) { const words = text.split(/\s+/); const lines: string[] = []; let line = ''; for (const word of words) { if ((line + ' ' + word).trim().length > max) { lines.push(line); line = word } else line = (line + ' ' + word).trim() } if (line) lines.push(line); return lines }

export async function POST(request: Request) {
  const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser()
  if (!user?.email?.toLowerCase().endsWith('@care-intrenational.org')) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  const parsed = schema.safeParse(await request.json()); if (!parsed.success) return NextResponse.json({ error: 'Complete all offer fields.' }, { status: 400 }); const input = parsed.data
  const hrReference = `CARE-${new Date().getUTCFullYear()}-${candidateIdFragment(input.submissionId)}`
  const { data: candidate } = await supabase.from('assessment_submissions').select('id,full_name,email,decision_status,offer_status,offer_request_key').eq('id', input.submissionId).maybeSingle()
  if (!candidate) return NextResponse.json({ error: 'Candidate not found.' }, { status: 404 }); if (candidate.decision_status !== 'passed') return NextResponse.json({ error: 'Offers can only be issued to passed candidates.' }, { status: 400 })
  const requestKey = `${candidate.id}:${input.startDate}:${hrReference}:${input.acceptanceDeadline}`; if (candidate.offer_status === 'sent' && candidate.offer_request_key === requestKey) return NextResponse.json({ message: 'Offer already sent.' })
  const { error: saving } = await supabase.from('assessment_submissions').update({ offer_status: 'generating', offer_error: null, offer_request_key: requestKey, offer_start_date: input.startDate, offer_duty_station: input.dutyStation, offer_department: input.department, offer_contract_type: input.contractType, offer_hr_reference: hrReference, offer_document_deadline: input.documentDeadline }).eq('id', candidate.id)
  if (saving) return NextResponse.json({ error: saving.message }, { status: 500 })

  const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const logo = await pdf.embedPng(await fs.readFile(path.join(process.cwd(), 'public/care-logo.png'))); const seal = await pdf.embedPng(await fs.readFile(path.join(process.cwd(), 'public/care-seal.png')))
  const size: [number, number] = [595.28, 841.89]; const navy = rgb(0.04, 0.16, 0.34); const orange = rgb(0.93, 0.39, 0.05); const ink = rgb(0.12, 0.14, 0.18); const muted = rgb(0.36, 0.4, 0.46)
  let pageNumber = 0; let page = pdf.addPage(size); pageNumber += 1; let y = 742
  const header = () => { page.drawImage(logo, { x: 45, y: 774, width: 128, height: 42 }); page.drawText('HUMAN RESOURCES', { x: 426, y: 794, size: 8, font: bold, color: navy }); page.drawText('CONDITIONAL OFFER', { x: 418, y: 781, size: 7, font, color: muted }); page.drawLine({ start: { x: 45, y: 766 }, end: { x: 550, y: 766 }, thickness: 2, color: orange }); page.drawImage(seal, { x: 198, y: 230, width: 200, height: 200, opacity: 0.075 }) }
  const footer = () => { page.drawLine({ start: { x: 45, y: 45 }, end: { x: 550, y: 45 }, thickness: 0.7, color: rgb(0.8, 0.82, 0.85) }); page.drawText('CARE International  |  Confidential recruitment document', { x: 45, y: 30, size: 7, font, color: muted }); page.drawText(`Page ${pageNumber} of 3`, { x: 487, y: 30, size: 7, font, color: muted }) }
  header(); const newPage = () => { footer(); page = pdf.addPage(size); pageNumber += 1; y = 742; header() }
  const draw = (text: string, textSize = 10, isBold = false, gap = 15) => { const lines = wrap(text, isBold ? 88 : 82); const lineHeight = gap; const blockHeight = lines.length * lineHeight + 12; if (y - blockHeight < 75) newPage(); if (!isBold) page.drawRectangle({ x: 48, y: y - blockHeight + 4, width: 5, height: blockHeight - 8, color: orange, opacity: 0.85 }); lines.forEach((line, index) => page.drawText(line, { x: isBold ? 55 : 62, y: y - index * lineHeight, size: textSize, font: isBold ? bold : font, color: isBold ? navy : ink })); y -= blockHeight }
  const label = (key: string, value: string) => { page.drawText(key, { x: 55, y, size: 8, font: bold, color: muted }); page.drawText(value, { x: 175, y, size: 9.5, font, color: ink }); y -= 18 }
  draw('CONDITIONAL OFFER OF EMPLOYMENT', 18, true, 23); draw(`Reference: ${hrReference}    Date: ${new Date().toLocaleDateString('en-GB')}`, 9, false, 14); y -= 5
  label('Candidate', input.applicantName); label('Position', input.jobTitle); label('Duty station', input.dutyStation); label('Department / programme', input.department); label('Contract type', input.contractType); label('Proposed start date', input.startDate)
  draw(`Dear ${input.applicantName},`); draw('Following completion of the applicable recruitment and selection process, CARE International is pleased to provide you with this conditional offer of employment. This offer is subject to satisfactory completion of the pre-employment and onboarding requirements set out in this letter.'); draw('1. CONDITIONS OF OFFER', 11, true); draw('This offer is conditional upon satisfactory verification of academic and professional qualifications; verification of references and employment history; confirmation of eligibility to work in the applicable duty station; completion of required compliance, safeguarding and background checks; and submission and verification of all required onboarding documentation.'); draw('2. CERTIFICATE & LANGUAGE REQUIREMENTS', 11, true); draw('Applicants are required to submit relevant academic, professional and training certificates in English, French and Portuguese, where applicable to the position or deployment requirements. Where an original certificate is not available in one or more required languages, the applicant is responsible for arranging a professional translation. CARE International does not provide direct sponsorship or advance payment for certificate translation. If you need documents translated into English, French or Portuguese, please contact Lingua Bridge at info@linguab.com or visit https://linguab.com. Eligible translation expenses may be considered for reimbursement, subject to applicable organisational procedures and submission of the original translation invoice, proof of payment and completed translated documents.'); draw('3. DOCUMENT SUBMISSION DEADLINE', 11, true); draw(`All requested documents must be submitted by ${input.documentDeadline}. Failure to provide required documentation, or submission of documents that cannot be satisfactorily verified, may result in a delay, amendment or withdrawal of this conditional offer.`); draw('4. ACCEPTANCE DEADLINE', 11, true); draw(`You must confirm your acceptance of this conditional offer by ${input.acceptanceDeadline}. Acceptance should be confirmed by signing and returning this letter to ${HR_CONTACT}. If acceptance is not received by the deadline, the offer may be considered to have lapsed.`); draw('5. FINAL APPOINTMENT', 11, true); draw('This conditional offer does not constitute a final appointment or employment contract. Final appointment is subject to satisfactory completion of all applicable recruitment, verification, compliance and onboarding requirements. The final terms and conditions of employment will be contained in the applicable employment agreement.'); draw('We look forward to completing the remaining requirements with you.')
  newPage(); draw('4. IMPORTANT INFORMATION', 11, true); draw('This conditional offer does not constitute a final appointment or employment contract. CARE International reserves the right to withdraw or amend this offer if any condition is not met or if information provided during the recruitment process is found to be inaccurate or incomplete.'); draw('Please keep a copy of the signed letter for your records. The signed and scanned copy must be returned using the instructions in the accompanying email.'); draw('Yours sincerely,'); y -= 24; page.drawLine({ start: { x: 55, y }, end: { x: 230, y }, thickness: 0.8, color: navy }); y -= 16; draw('Human Resources - CARE International'); draw('CARE International is committed to safeguarding and to the highest standards of integrity, accountability and respect.', 9, false, 13)
  newPage(); page.drawImage(seal, { x: 382, y: 575, width: 145, height: 145, opacity: 0.68 }); draw('APPLICANT ACCEPTANCE', 15, true, 22); draw('I, ________________________________________________, acknowledge receipt of this conditional offer and confirm my intention to accept the offer subject to the conditions stated above.'); y -= 15; label('Applicant name', input.applicantName); label('Applicant signature', '________________________________'); label('Date', '________________________________'); label('Date/time received', '________________________________'); label('Acceptance deadline', input.acceptanceDeadline); y -= 15; draw('Applicant signature (ink)', 9, true); page.drawLine({ start: { x: 55, y: y - 20 }, end: { x: 300, y: y - 20 }, thickness: 0.8, color: ink }); y -= 34; draw('Signature date', 9, true); page.drawLine({ start: { x: 55, y: y - 20 }, end: { x: 300, y: y - 20 }, thickness: 0.8, color: ink }); y -= 34; draw("Return instructions: download this PDF, print it, sign it in ink, scan the signed document, and email the scanned copy back to Human Resources using the reply email address.", 10, false, 16); footer();
  const bytes = await pdf.save(); const safeName = candidate.full_name.replace(/[^a-z0-9]+/gi, '-').toLowerCase()
  const sent = await resend.emails.send({ from: 'CARE International <careers@care-intrenational.org>', to: [candidate.email], subject: `Conditional Offer of Employment | ${hrReference}`, text: `Dear ${input.applicantName},\n\nCONDITIONAL OFFER OF EMPLOYMENT\nReference: ${hrReference}\nPosition: ${input.jobTitle}\n\nCongratulations. Following completion of our recruitment and selection process, CARE International is pleased to share your conditional offer of employment.\n\nPLEASE READ CAREFULLY\nThe attached PDF contains the complete terms and conditions of your conditional offer. Please review every page and retain a copy for your records.\n\nHOW TO ACCEPT\n1. Download and print the attached offer letter.\n2. Sign the applicant acceptance page using ink.\n3. Scan the complete signed document clearly.\n4. Reply to this email with the scanned signed copy attached by ${input.acceptanceDeadline}.\n\nPlease do not return an unsigned document or an acceptance completed only by typing your name. Your appointment remains conditional until the applicable requirements are completed and confirmed by Human Resources.\n\nDOCUMENT TRANSLATION\nIf any required documents need translation into English, French or Portuguese, please contact Lingua Bridge at info@linguab.com or visit https://linguab.com.\n\nQUESTIONS\nFor questions, reply to this email and quote HR reference ${hrReference}.\n\nKind regards,\n\n${HR_CONTACT}\nCARE International`, attachments: [{ filename: `conditional-offer-${safeName}.pdf`, content: Buffer.from(bytes).toString('base64') }] })
  if (sent.error) { await supabase.from('assessment_submissions').update({ offer_status: 'failed', offer_error: sent.error.message }).eq('id', candidate.id); return NextResponse.json({ error: sent.error.message }, { status: 502 }) }
  const { error: finalError } = await supabase.from('assessment_submissions').update({ offer_status: 'sent', offer_sent_at: new Date().toISOString(), offer_error: null }).eq('id', candidate.id)
  if (finalError) return NextResponse.json({ error: `Offer sent but status could not be saved: ${finalError.message}` }, { status: 500 })
  return NextResponse.json({ message: 'Offer letter sent.' })
}
