import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import AdminSidebar from '@/components/admin-sidebar'
import { createClient } from '@/lib/supabase/server'

export default async function InterviewDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/admin/login')
  const { data: interview } = await supabase.from('interview_sessions').select('*').eq('id', id).maybeSingle()
  if (!interview) notFound()
  const assessment = interview.assessment as { summary?: string; strengths?: string[]; concerns?: string[]; scores?: Record<string, number>; recommendation?: string } | null
  const transcript = (interview.transcript as { speaker: string; text: string }[]) || []
  return <div className="min-h-screen bg-[#faf8f2] lg:flex"><AdminSidebar /><main className="min-w-0 flex-1 p-6 lg:p-12"><Link href="/admin/interviews" className="text-sm font-semibold text-[#455c7d]">← Back to interviews</Link><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#f47700]">Interview review</p><h1 className="mt-2 text-4xl font-semibold text-[#101b30]">{interview.candidate_name}</h1><p className="mt-2 text-[#455c7d]">{interview.role}</p></div><div className="flex gap-2"><form action={`/api/admin/interviews/${id}/decision`} method="post"><input type="hidden" name="decision" value="passed" /><button className="rounded-xl bg-[#36835d] px-4 py-2 font-semibold text-white">Mark passed</button></form><form action={`/api/admin/interviews/${id}/decision`} method="post"><input type="hidden" name="decision" value="failed" /><button className="rounded-xl border border-red-200 bg-red-50 px-4 py-2 font-semibold text-red-700">Mark failed</button></form></div></div><div className="mt-8 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><section className="rounded-[28px] border border-[#ded8ca] bg-white p-6"><h2 className="text-2xl font-semibold text-[#101b30]">Interview transcript</h2><div className="mt-5 grid gap-4">{transcript.map((turn, index) => <div key={index} className="rounded-2xl bg-[#f7f8f6] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#f47700]">{turn.speaker}</p><p className="mt-2 leading-7 text-[#455c7d]">{turn.text}</p></div>)}</div></section><aside className="grid gap-6"><section className="rounded-[28px] border border-[#ded8ca] bg-white p-6"><h2 className="text-2xl font-semibold text-[#101b30]">Score</h2><p className="mt-3 text-[#455c7d]">{assessment?.summary || 'No summary available.'}</p><div className="mt-5 grid gap-3">{Object.entries(assessment?.scores || {}).map(([label, score]) => <div key={label} className="flex items-center justify-between rounded-xl bg-[#f7f8f6] px-4 py-3"><span className="capitalize text-[#455c7d]">{label.replace(/([A-Z])/g, ' $1')}</span><strong className="text-[#101b30]">{score}/5</strong></div>)}</div><p className="mt-5 rounded-xl bg-[#eaf4ed] p-3 font-semibold text-[#36835d]">{assessment?.recommendation || 'Pending recommendation'}</p></section><section className="rounded-[28px] border border-[#ded8ca] bg-white p-6"><h2 className="text-xl font-semibold text-[#101b30]">Issue skills assessment</h2><p className="mt-2 text-sm text-[#455c7d]">Send an assessment link to this applicant from the Assessments section, then track the result here.</p><Link href="/admin?section=Assessments" className="mt-4 inline-flex rounded-xl bg-[#f47700] px-4 py-2 font-semibold text-white">Choose assessment</Link></section></aside></div></main></div>
}
